[package]
name = "crx-convert"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4"
crx = { path = "../../lib/crx", features = [ "to_image" ] }
clap = { version = "4.1.8", features = [ "derive" ] }
flate2 = "1.0"
image = { version = "0.24", default-features = false, features = [ "png" ] }
owo-colors = "3"
rayon = "1.7"
