name: Build Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'
      - '!.github/workflows/test.yml'
      - 'LICENSE'
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'
      - '!.github/workflows/test.yml'
      - 'LICENSE'
      - '**/README.md'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run tests
        run: cargo test --verbose --workspace
